import Head from 'next/head';
import { motion } from 'framer-motion';
import { Carousel } from 'flowbite-react';
import { useRouter } from 'next/router';

export default function Home() {
    const router = useRouter();
    return (
        <div>
            <Head>
                <title>college management system</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="hero min-h-[50vh] container mx-auto bg-base-200">
                <div className="hero-content text-center">
                    <div className="max-w-xl">
                        <h1 className="text-5xl font-bold">
                            College Management System
                        </h1>
                        <p className="py-6">
                            Provident cupiditate voluptatem et in. Quaerat
                            fugiat ut assumenda excepturi exercitationem quasi.
                            In deleniti eaque aut repudiandae et a id nisi.
                        </p>
                        <button
                            className="btn btn-primary"
                            onClick={() => router.push('/signin')}
                        >
                            Get Started
                        </button>
                    </div>
                </div>
            </div>

            <div className="h-56 sm:h-64 xl:h-80 2xl:h-96 container mx-auto my-3">
                <Carousel slideInterval={3000}>
                    <motion.img
                        src="https://flowbite.com/docs/images/carousel/carousel-1.svg"
                        alt="..."
                        className="h-56 sm:h-64 xl:h-80 2xl:h-96"
                    />

                    <motion.img
                        src="https://flowbite.com/docs/images/carousel/carousel-2.svg"
                        alt="..."
                        className="h-56 sm:h-64 xl:h-80 2xl:h-96"
                    />
                    <motion.img
                        src="https://flowbite.com/docs/images/carousel/carousel-3.svg"
                        alt="..."
                        className="h-56 sm:h-64 xl:h-80 2xl:h-96"
                    />
                    <motion.img
                        src="https://flowbite.com/docs/images/carousel/carousel-4.svg"
                        alt="..."
                        className="h-56 sm:h-64 xl:h-80 2xl:h-96"
                    />
                </Carousel>
            </div>
        </div>
    );
}
